name: C/C++ CI

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: matt-attack/pubsub
        path: pubsub
    - uses: actions/checkout@v2
      with:
        repository: matt-attack/rucksack
        path: rucksack
    - uses: actions/checkout@v2
      with:
        path: pubviz
    - run: ls
    - run: ls pubsub
    - run: ls rucksack
    - run: ls pubviz
    - name: build pubsub
      run: |
        cd pubsub
        cmake .
        cmake --build .
    - name: build rucksack
      run: |
        cd rucksack
        cmake .
        cmake --build .
    - name: build pubviz
      run: |
        cd pubviz
        cmake .
        cmake --build .
