name: C/C++ CI

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: install deps
      run: sudo apt-get install libxcursor-dev mesa-common-dev libglu1-mesa-dev libfreeimage-dev libglewmx-dev
    - uses: actions/checkout@v2
      with:
        repository: matt-attack/pubsub
        path: pubsub
    - uses: actions/checkout@v2
      with:
        repository: matt-attack/gwen
        path: gwen
    - uses: actions/checkout@v2
      with:
        repository: matt-attack/rucksack
        path: rucksack
    - uses: actions/checkout@v2
      with:
        path: pubviz
    - run: ls
    - run: ls pubsub
    - run: ls rucksack
    - run: ls pubviz
    - run: ls gwen
    - name: build gwen
      run: |
        cd gwen/gwen
        cmake .
        cmake --build . -j $(nproc)
    - name: build pubsub
      run: |
        cd pubsub
        cmake .
        cmake --build . -j $(nproc)
    - name: build rucksack
      run: |
        cd rucksack
        cmake .
        cmake --build . -j $(nproc)
    - name: build pubviz
      run: |
        cd pubviz
        cmake .
        cmake --build . -j $(nproc)
